services:
    _defaults:
        autowire: true
        autoconfigure: true

    # OnGenerateWidgetListener
    Esit\Selectwizard\Classes\Listener\OnGenerateWidgetListener:
        tags:
            - { name: kernel.event_listener, event: Esit\Selectwizard\Classes\Events\OnGenerateWidgetEvent, method: insertCss, priority: 7168 }
            - { name: kernel.event_listener, event: Esit\Selectwizard\Classes\Events\OnGenerateWidgetEvent, method: insertJs, priority: 6144 }
            - { name: kernel.event_listener, event: Esit\Selectwizard\Classes\Events\OnGenerateWidgetEvent, method: generateWidgets, priority: 5120 }
            - { name: kernel.event_listener, event: Esit\Selectwizard\Classes\Events\OnGenerateWidgetEvent, method: createTemplate, priority: 3072 }
            - { name: kernel.event_listener, event: Esit\Selectwizard\Classes\Events\OnGenerateWidgetEvent, method: addDataToTemplate, priority: 2048 }
            - { name: kernel.event_listener, event: Esit\Selectwizard\Classes\Events\OnGenerateWidgetEvent, method: parseOutput, priority: 1024 }



