##
# @package     selectwizard
# @filesource  services.yml
# @version     1.0.0
# @since       14.02.2020 - 10:26
# @author      Patrick Froch <info@easySolutionsIT.de>
# @link        http://easySolutionsIT.de
# @copyright   e@sy Solutions IT 2020
# @license     LGPLv3
##

# Services
services:
    _defaults:
        autowire: true
        autoconfigure: tru

    Esit\Selectwizard\Classes\Services\AssetHandler:

    Esit\Selectwizard\Classes\Services\SelectHandler:

    Esit\Selectwizard\Classes\Services\TemplateFactory: